import indexData from "@/data/leetcode/index.json";

/**
 * Lightweight, client-safe entry used for the /leetcode listing, search,
 * the landing-page callout, and the command palette — generated by
 * scripts/generate-leetcode-index.mjs. Deliberately has no `node:fs`
 * import (unlike src/lib/leetcode-problem.ts) so it can be pulled into
 * client components without breaking the browser bundle.
 */
export interface LeetCodeIndexEntry {
  number: number;
  slug: string;
  title: string;
  excerpt: string;
}

export const leetcodeIndex: LeetCodeIndexEntry[] = indexData as LeetCodeIndexEntry[];
