export interface NavItem {
  slug: string;
  title: string;
  href: string;
  category: "structure" | "pattern" | "page";
  description: string;
}

export const NAV_ITEMS: NavItem[] = [
  {
    slug: "home",
    title: "Home",
    href: "/",
    category: "page",
    description: "Landing page",
  },
  {
    slug: "design-system",
    title: "Design System",
    href: "/design-system",
    category: "page",
    description: "UI component showcase",
  },
  {
    slug: "arrays",
    title: "Arrays & Sorting",
    href: "/dsa/arrays",
    category: "structure",
    description: "Bubble, insertion, merge, quick sort & binary search",
  },
  {
    slug: "linked-lists",
    title: "Linked Lists",
    href: "/dsa/linked-lists",
    category: "structure",
    description: "Singly linked list insert / delete / reverse / search",
  },
  {
    slug: "binary-search-trees",
    title: "Binary Search Trees",
    href: "/dsa/binary-search-trees",
    category: "structure",
    description: "BST insert, delete, search, traversals",
  },
  {
    slug: "stacks",
    title: "Stacks",
    href: "/dsa/stacks",
    category: "structure",
    description: "Push, pop, peek, and balanced parentheses via LIFO",
  },
  {
    slug: "queues",
    title: "Queues",
    href: "/dsa/queues",
    category: "structure",
    description: "Simple & circular queues with wraparound",
  },
  {
    slug: "hash-tables",
    title: "Hash Tables",
    href: "/dsa/hash-tables",
    category: "structure",
    description: "Hashing, chaining collisions, load factor & resize",
  },
  {
    slug: "two-pointers",
    title: "Two Pointers",
    href: "/patterns/two-pointers",
    category: "pattern",
    description: "Converging / diverging pointer techniques",
  },
  {
    slug: "sliding-window",
    title: "Sliding Window",
    href: "/patterns/sliding-window",
    category: "pattern",
    description: "Fixed & variable size window scanning",
  },
  {
    slug: "tree-bfs",
    title: "Tree BFS",
    href: "/patterns/tree-bfs",
    category: "pattern",
    description: "Level-order traversal pattern",
  },
  {
    slug: "fast-slow-pointers",
    title: "Fast & Slow Pointers",
    href: "/patterns/fast-slow-pointers",
    category: "pattern",
    description: "Cycle detection & finding the middle in one pass",
  },
  {
    slug: "monotonic-stack",
    title: "Monotonic Stack",
    href: "/patterns/monotonic-stack",
    category: "pattern",
    description: "Next greater/smaller element in O(n)",
  },
  {
    slug: "heaps",
    title: "Heaps",
    href: "/dsa/heaps",
    category: "structure",
    description: "Min/max heap insert & extract, array + tree views in sync",
  },
  {
    slug: "graphs",
    title: "Graphs",
    href: "/dsa/graphs",
    category: "structure",
    description: "Adjacency list, BFS & DFS traversal",
  },
  {
    slug: "tries",
    title: "Tries",
    href: "/dsa/tries",
    category: "structure",
    description: "Prefix tree insert & search with word-path highlighting",
  },
  {
    slug: "merge-intervals",
    title: "Merge Intervals",
    href: "/patterns/merge-intervals",
    category: "pattern",
    description: "Sort + sweep overlapping ranges into merged intervals",
  },
  {
    slug: "top-k-elements",
    title: "Top K Elements",
    href: "/patterns/top-k-elements",
    category: "pattern",
    description: "Size-k heap keeps the K largest/smallest without a full sort",
  },
  {
    slug: "union-find",
    title: "Union-Find (Disjoint Set)",
    href: "/dsa/union-find",
    category: "structure",
    description: "Union by rank + path compression, forest-of-trees visualization",
  },
  {
    slug: "shortest-paths",
    title: "Shortest Paths (Dijkstra)",
    href: "/dsa/shortest-paths",
    category: "structure",
    description: "Dijkstra's algorithm with a live distance table synced to the graph",
  },
  {
    slug: "backtracking",
    title: "Backtracking",
    href: "/dsa/backtracking",
    category: "structure",
    description: "Recursion tree + call stack, visualized live via subset generation",
  },
  {
    slug: "modified-binary-search",
    title: "Modified Binary Search",
    href: "/patterns/modified-binary-search",
    category: "pattern",
    description: "Search a rotated sorted array by finding which half is sorted",
  },
  {
    slug: "subsets",
    title: "Subsets (Backtracking)",
    href: "/patterns/subsets",
    category: "pattern",
    description: "Include/exclude recursion tree generating every subset",
  },
  {
    slug: "avl-trees",
    title: "AVL Trees",
    href: "/dsa/avl-trees",
    category: "structure",
    description: "Self-balancing BST with height/balance-factor tracking and LL/RR/LR/RL rotations",
  },
  {
    slug: "red-black-trees",
    title: "Red-Black Trees",
    href: "/dsa/red-black-trees",
    category: "structure",
    description: "Self-balancing BST via color-based invariants, insertion fixup with recoloring + rotations",
  },
  {
    slug: "segment-trees",
    title: "Segment Trees",
    href: "/dsa/segment-trees",
    category: "structure",
    description: "Range-sum queries and point updates in O(log n), array + tree views in sync",
  },
  {
    slug: "fenwick-trees",
    title: "Fenwick Trees",
    href: "/dsa/fenwick-trees",
    category: "structure",
    description: "Binary indexed tree — prefix sums and point updates via lowbit index jumps",
  },
  {
    slug: "skip-lists",
    title: "Skip Lists",
    href: "/dsa/skip-lists",
    category: "structure",
    description: "Layered linked list with probabilistic levels and a drop-down search path",
  },
  {
    slug: "bloom-filters",
    title: "Bloom Filters",
    href: "/dsa/bloom-filters",
    category: "structure",
    description: "Probabilistic set membership via a shared bit array and multiple hash functions",
  },
  {
    slug: "lru-cache",
    title: "LRU Cache",
    href: "/dsa/lru-cache",
    category: "structure",
    description: "Hash map + doubly linked list kept in sync for O(1) get/put with LRU eviction",
  },
  {
    slug: "minimum-spanning-tree",
    title: "Minimum Spanning Tree",
    href: "/dsa/minimum-spanning-tree",
    category: "structure",
    description: "Prim's and Kruskal's algorithms, side by side on the same weighted graph",
  },
  {
    slug: "topological-sort",
    title: "Topological Sort",
    href: "/dsa/topological-sort",
    category: "structure",
    description: "Kahn's algorithm — in-degree counting and a zero-in-degree queue over a DAG",
  },
  {
    slug: "bellman-ford",
    title: "Bellman-Ford",
    href: "/dsa/bellman-ford",
    category: "structure",
    description: "Single-source shortest paths with negative edge weights and negative-cycle detection",
  },
  {
    slug: "floyd-warshall",
    title: "Floyd-Warshall",
    href: "/dsa/floyd-warshall",
    category: "structure",
    description: "All-pairs shortest paths via dynamic programming over an NxN distance matrix",
  },
];

export const STRUCTURE_ITEMS = NAV_ITEMS.filter((i) => i.category === "structure");
export const PATTERN_ITEMS = NAV_ITEMS.filter((i) => i.category === "pattern");
